### ISSUE TITLE
Does not support 64-bit integers

### ISSUE THREAD

**Issue by timvermeulen** [vapor/sqlite#17]
I have no idea how easy this is to fix, but currently an exception is thrown when an integer that exceeds `Int32.max` is passed to `bind(_:)` (https://github.com/vapor/sqlite/blob/master/Sources/SQLite/SQLite%2BStatement.swift#L39-L43). This (seemingly) makes it impossible to store 64-bit integers, which SQLite does natively support.

**Comment by tanner0101** [comment]
Looks like this may be as simple as changing that to `sqlite3_bind_int64`.

**Comment by tanner0101** [comment]
@timvermeulen tagging this as 2.0.1. Can you verify that it fixes your issue when you get a chance?

**Comment by timvermeulen** [comment]
Doesn't solve it, unfortunately – it prevents the crash, but it only saves the lower 32 bits of the integer. 😕

**Comment by tanner0101** [comment]
Could you submit a failing test case that reproduces that bug? 

Also maybe as a temporary solution try binding the integer as a string?

**Comment by timvermeulen** [comment]
Just did a PR. My temporary solution is just to not use the in-memory database 😅

**Comment by tanner0101** [comment]
Forgot to add `int64` to the fetching. Fixed here: https://github.com/vapor/sqlite/pull/20

**Comment by timvermeulen** [comment]
Awesome, works perfectly.
