### ISSUE TITLE
Extend Bool to conform to SQLiteDataConvertible

### ISSUE THREAD

**Issue by wmcginty** [vapor/sqlite#35]
Currently on 3.0.0 RC2.3, it appears that Bool is unusable as an SQLite storage type. Using a model like this below, results in an error:

FluentSQLiteError.queryDataSerialize: Cannot serialize Bool to SQLiteData (SQLiteDatabase+Query.swift:104)

```swift
struct Project: Content, SQLiteUUIDModel, Migration {
    
    //MARK: Properties
    var id: UUID?
    var name: String
    var isActive: Bool
    var groupID: UUID?
}
```

I can fix the issue by creating an extension on Bool to conform to SQLiteDataConvertible, similar to:

```swift
enum SQLiteBoolError: Error {
    case inconvertibleBool
}

extension Bool: SQLiteDataConvertible {
    
    /// See `SQLiteDataConvertible.convertFromSQLiteData(_:)`
    public static func convertFromSQLiteData(_ data: SQLiteData) throws -> Bool {
        switch data {
        case .integer(let integer): return integer != 0 ? true : false
        default: throw SQLiteBoolError.inconvertibleBool
        }
    }
    
    /// See `convertToSQLiteData()`
    public func convertToSQLiteData() throws -> SQLiteData {
        let state = self == false ? 0 : 1
        return SQLiteData.integer(state)
    }
}
```

Is the inability to use Bool by default intentional? If not, is this a worthwhile enhancement to submit as a PR?

**Comment by 0xTim** [comment]
Just released https://github.com/vapor/sqlite/releases/tag/3.0.0-rc.2.4
