### ISSUE TITLE
SQLiteConnection.lastAutoincrementID is not threadsafe

### ISSUE THREAD

**Issue by ffried** [vapor/sqlite#51]
`sqlite3_last_insert_rowid` describes in its header-doc that it's not thread-safe and might return a different ID if another thread is performing an insert at the same time. When e.g. using a DatabaseConnetionPool, there's only one database (hence only one sqlite handle) with multiple connections accessing it. If two connections now perform an insert, it might happen that the former receives the ID of the latter. This leads to `Model`s having a wrong ID.

**Comment by tanner0101** [comment]
Moving this issue to vapor/sqlite since that's where the call to `sqlite3_last_insert_rowid` happens.

**Comment by tanner0101** [comment]
Now that each connection has it's own `handle` (thanks to https://github.com/vapor/sqlite/pull/50), I think this issue is resolved. 

@ffried could you try out [3.2.0](https://github.com/vapor/sqlite/releases/tag/3.2.0) to verify?

**Comment by ffried** [comment]
Interesting, thanks for the info! I'll try it and update / close this bug depending on the results.

**Comment by ffried** [comment]
It seems like this bug is fixed, yes. I didn't run into this problem anymore since upgrading to 3.2.0 and removing our workaround.
